refunded = {
    "type": "mobileOrder",
    "order_id": "yxncskffan5k1",
    "user_id": "57927099417606817",
    "state": "REFUNDED",
    "cancel_until": "2024-10-31T16:00:00Z",
    "redeem_interval": {"start": "2024-10-31T17:40:00Z", "end": "2024-10-31T22:10:00Z"},
    "pickup_interval": {"start": "2024-10-31T18:00:00Z", "end": "2024-10-31T22:00:00Z"},
    "store_time_zone": "America/Toronto",
    "quantity": 2,
    "price_including_taxes": {"code": "CAD", "minor_units": 1806, "decimals": 2},
    "price_excluding_taxes": {"code": "CAD", "minor_units": 1598, "decimals": 2},
    "total_applied_taxes": {"code": "CAD", "minor_units": 208, "decimals": 2},
    "sales_taxes": [{...}],
    "total_price": {"code": "CAD", "minor_units": 1806, "decimals": 2},
    "pickup_location": {...},
    "can_be_rated": False,
    "is_rated": True,
    "should_be_excluded_from_expense_rating": False,
    "overall_rating": 5,
    "time_of_purchase": "2024-10-30T23:47:45Z",
    "store_id": "48448666653255777",
    "store_name": "Eataly - Don Mills",
    "store_branch": "",
    "store_logo": {...},
    "item_id": "48448667190123489",
    "item_name": "Assorted Prepared Foods",
    "item_category": "MEAL",
    "item_logo": {...},
    "item_cover_image": {...},
    "food_handling_instructions": "",
    "is_buffet": False,
    "item_collection_info": "The pick up location will be at the Restaurant Host stand. To the left, upon entrance",
    "can_user_supply_packaging": False,
    "packaging_option": "CANT_BRING_ANYTHING",
    "pickup_window_changed": False,
    "can_show_best_before_explainer": False,
    "show_sales_taxes": True,
    "order_type": "MAGICBAG",
    "is_support_available": True,
    "redeeming_user_id": "128974371",
    "has_dynamic_price": False,
    "is_eligible_for_reward": False,
    "last_updated_at_utc": "2024-11-06T10:23:05Z",
    "redeemed_at_utc": "2024-10-31T19:18:33Z",
    "has_multiple_payments": False,
    "total_price_paid_with_external_provider": {"code": "CAD", "minor_units": 1806, "decimals": 2},
    # 'total_price_paid_with_voucher': None,
    "payment_method_display_name": "Google Pay: Mastercard",
    "payment_state": "MONEY_RETURNED",
    "cancelling_entity": "ADMIN",
    "expected_bank_processing_days": 14,
    "cancelled_or_refunded_at_utc": "2024-11-06T10:23:05Z",
    "support_request_created_at_utc": "2024-11-02T00:45:43Z",
    "is_donation": False,
}
