active = {
    "type": "mobileOrder",
    "order_id": "36gf35hqdg021",
    "user_id": "79137842859637953",
    "state": "ACTIVE",
    "cancel_until": "2024-12-30T17:00:00Z",
    "redeem_interval": {"start": "2024-12-30T18:40:00Z", "end": "2024-12-30T23:10:00Z"},
    "pickup_interval": {"start": "2024-12-30T19:00:00Z", "end": "2024-12-30T23:00:00Z"},
    "store_time_zone": "America/Toronto",
    "quantity": 2,
    "price_including_taxes": {"code": "CAD", "minor_units": 1598, "decimals": 2},
    "price_excluding_taxes": {"code": "CAD", "minor_units": 1598, "decimals": 2},
    "total_applied_taxes": {"code": "CAD", "minor_units": 0, "decimals": 2},
    "sales_taxes": [{...}],
    "total_price": {"code": "CAD", "minor_units": 1598, "decimals": 2},
    "pickup_location": {...},
    "can_be_rated": False,
    "is_rated": False,
    "should_be_excluded_from_expense_rating": False,
    # 'overall_rating': None,
    "time_of_purchase": "2024-12-29T23:20:57Z",
    "store_id": "504081",
    "store_name": "McEwan Foods - Don Mills",
    "store_branch": "",
    "store_logo": {...},
    "item_id": "377070",
    "item_name": "Surprise Bag",
    "item_category": "OTHER",
    "item_logo": {...},
    "item_cover_image": {...},
    "food_handling_instructions": "",
    "is_buffet": False,
    "item_collection_info": "",
    "can_user_supply_packaging": False,
    "packaging_option": "BAG_ALLOWED",
    "pickup_window_changed": False,
    "can_show_best_before_explainer": False,
    "show_sales_taxes": True,
    "order_type": "MAGICBAG",
    "is_support_available": True,
    # 'redeeming_user_id': None,
    "has_dynamic_price": False,
    "is_eligible_for_reward": False,
    "last_updated_at_utc": "2024-12-29T23:20:57Z",
    # 'redeemed_at_utc': None,
    "has_multiple_payments": True,
    # 'total_price_paid_with_external_provider': None,
    "total_price_paid_with_voucher": {"code": "CAD", "minor_units": 1598, "decimals": 2},
    "payment_method_display_name": "Voucher",
    # 'payment_state': None,
    # 'cancelling_entity': None,
    # 'expected_bank_processing_days': None,
    # 'cancelled_or_refunded_at_utc': None,
    # 'support_request_created_at_utc': None,
    "is_donation": False,
}
