cancelled = {
    "type": "mobileOrder",
    "order_id": "r3e5zkg12eg91",
    "user_id": "79137842859637953",
    "state": "CANCELLED",
    "cancel_until": "2025-04-24T13:15:00Z",
    "redeem_interval": {"start": "2025-04-24T14:55:00Z", "end": "2025-04-25T00:40:00Z"},
    "pickup_interval": {"start": "2025-04-24T15:15:00Z", "end": "2025-04-25T00:30:00Z"},
    "store_time_zone": "America/Toronto",
    "quantity": 1,
    "price_including_taxes": {"code": "CAD", "minor_units": 1581, "decimals": 2},
    "price_excluding_taxes": {"code": "CAD", "minor_units": 1399, "decimals": 2},
    "total_applied_taxes": {"code": "CAD", "minor_units": 182, "decimals": 2},
    "sales_taxes": [{...}],
    "total_price": {"code": "CAD", "minor_units": 1581, "decimals": 2},
    "pickup_location": {...},
    "can_be_rated": False,
    "is_rated": False,
    "should_be_excluded_from_expense_rating": False,
    # 'overall_rating': None,
    "time_of_purchase": "2025-04-24T15:17:22Z",
    "store_id": "85791842776430465",
    "store_name": "Nonna Lia",
    "store_branch": "Oakwood",
    "store_logo": {...},
    "item_id": "85794643630215137",
    "item_name": "Double Dessert Bag",
    "item_category": "MEAL",
    "item_logo": {...},
    "item_cover_image": {...},
    "food_handling_instructions": "May contain nuts",
    "is_buffet": False,
    "item_collection_info": "",
    "can_user_supply_packaging": False,
    "packaging_option": "MUST_BRING_BAG",
    "pickup_window_changed": False,
    "can_show_best_before_explainer": False,
    "show_sales_taxes": True,
    "order_type": "MAGICBAG",
    "is_support_available": True,
    # 'redeeming_user_id': None,
    "has_dynamic_price": False,
    "is_eligible_for_reward": False,
    "last_updated_at_utc": "2025-04-24T15:17:57Z",
    # 'redeemed_at_utc': None,
    "has_multiple_payments": True,
    # 'total_price_paid_with_external_provider': None,
    "total_price_paid_with_voucher": {"code": "CAD", "minor_units": 1581, "decimals": 2},
    "payment_method_display_name": "Voucher",
    # 'payment_state': None,
    # 'cancelling_entity': None,
    # 'expected_bank_processing_days': None,
    # 'cancelled_or_refunded_at_utc': None,
    "support_request_created_at_utc": "2025-04-24T15:17:56Z",
    "is_donation": False,
}
