redeemed = {
    "type": "mobileOrder",
    "order_id": "adbfwse5db801",
    "user_id": "79137842859637953",
    "state": "REDEEMED",
    "cancel_until": "2024-12-20T18:00:00Z",
    "redeem_interval": {"start": "2024-12-20T19:40:00Z", "end": "2024-12-20T23:10:00Z"},
    "pickup_interval": {"start": "2024-12-20T20:00:00Z", "end": "2024-12-20T23:00:00Z"},
    "store_time_zone": "America/Toronto",
    "quantity": 1,
    "price_including_taxes": {"code": "CAD", "minor_units": 699, "decimals": 2},
    "price_excluding_taxes": {"code": "CAD", "minor_units": 699, "decimals": 2},
    "total_applied_taxes": {"code": "CAD", "minor_units": 0, "decimals": 2},
    "sales_taxes": [{...}],
    "total_price": {"code": "CAD", "minor_units": 699, "decimals": 2},
    "pickup_location": {...},
    "can_be_rated": True,
    "is_rated": True,
    "should_be_excluded_from_expense_rating": False,
    "overall_rating": 4,
    "time_of_purchase": "2024-12-20T18:10:57Z",
    "store_id": "914375",
    "store_name": "Metro - 15 Ellesmere Rd",
    "store_branch": "",
    "store_logo": {...},
    "item_id": "944930",
    "item_name": "Assorted Fruit & Salad",
    "item_category": "GROCERIES",
    "item_logo": {...},
    "item_cover_image": {...},
    # 'food_handling_instructions': None,
    "is_buffet": False,
    "item_collection_info": "Please proceed to the Service Desk to pick-up your Surprise Bag.",
    "can_user_supply_packaging": False,
    "packaging_option": "BAG_ALLOWED",
    "pickup_window_changed": False,
    "can_show_best_before_explainer": False,
    "show_sales_taxes": True,
    "order_type": "MAGICBAG",
    "is_support_available": True,
    "redeeming_user_id": "79137842859637953",
    "has_dynamic_price": False,
    "is_eligible_for_reward": False,
    "last_updated_at_utc": "2024-12-21T02:04:07Z",
    "redeemed_at_utc": "2024-12-20T20:49:55Z",
    "has_multiple_payments": True,
    # 'total_price_paid_with_external_provider': None,
    "total_price_paid_with_voucher": {"code": "CAD", "minor_units": 699, "decimals": 2},
    "payment_method_display_name": "Voucher",
    # 'payment_state': None,
    # 'cancelling_entity': None,
    # 'expected_bank_processing_days': None,
    # 'cancelled_or_refunded_at_utc': None,
    # 'support_request_created_at_utc': None,
    "is_donation": False,
}
