redeemed = {
    "type": "mobileOrder",
    "order_id": "kjr79m904rxz1",
    "user_id": "79137842859637953",
    "state": "REDEEMED",
    "cancel_until": "2025-04-24T11:00:00Z",
    "redeem_interval": {"start": "2025-04-24T12:40:00Z", "end": "2025-04-24T18:10:00Z"},
    "pickup_interval": {"start": "2025-04-24T13:00:00Z", "end": "2025-04-24T18:00:00Z"},
    "store_time_zone": "America/Toronto",
    "quantity": 1,
    "price_including_taxes": {"code": "CAD", "minor_units": 1129, "decimals": 2},
    "price_excluding_taxes": {"code": "CAD", "minor_units": 999, "decimals": 2},
    "total_applied_taxes": {"code": "CAD", "minor_units": 130, "decimals": 2},
    "sales_taxes": [{...}],
    "total_price": {"code": "CAD", "minor_units": 1129, "decimals": 2},
    "pickup_location": {...},
    "can_be_rated": False,
    "is_rated": False,
    "should_be_excluded_from_expense_rating": False,
    # 'overall_rating': None,
    "time_of_purchase": "2025-04-24T13:44:01Z",
    "store_id": "964080",
    "store_name": "Rosedale's Finest Specialty Foods",
    "store_branch": "",
    "store_logo": {...},
    "item_id": "909343",
    "item_name": "Large Surprise Bag",
    "item_category": "OTHER",
    # "item_logo": None,
    "item_cover_image": {...},
    "food_handling_instructions": "",
    "is_buffet": False,
    "item_collection_info": " For pickups, see our kitchen staff upstairs and present them with your code. Pick up hours change daily. ",
    "can_user_supply_packaging": False,
    "packaging_option": "BAG_ALLOWED",
    "pickup_window_changed": False,
    "can_show_best_before_explainer": False,
    "show_sales_taxes": True,
    "order_type": "MAGICBAG",
    "is_support_available": True,
    "redeeming_user_id": "57927099417606817",
    "has_dynamic_price": False,
    "is_eligible_for_reward": False,
    "last_updated_at_utc": "2025-04-24T17:22:31Z",
    "redeemed_at_utc": "2025-04-24T17:22:31Z",
    "has_multiple_payments": True,
    # 'total_price_paid_with_external_provider': None,
    "total_price_paid_with_voucher": {"code": "CAD", "minor_units": 1129, "decimals": 2},
    "payment_method_display_name": "Voucher",
    # 'payment_state': None,
    # 'cancelling_entity': None,
    # 'expected_bank_processing_days': None,
    # 'cancelled_or_refunded_at_utc': None,
    # 'support_request_created_at_utc': None,
    "is_donation": False,
}
