redeemed = {
    "type": "mobileOrder",
    "order_id": "hb46q61t344n1",
    "user_id": "79137842859637953",
    "state": "REDEEMED",
    "cancel_until": "2025-04-30T17:30:00Z",
    "redeem_interval": {"start": "2025-04-30T19:10:00Z", "end": "2025-04-30T22:10:00Z"},
    "pickup_interval": {"start": "2025-04-30T19:30:00Z", "end": "2025-04-30T22:00:00Z"},
    "store_time_zone": "America/Toronto",
    "quantity": 1,
    "price_including_taxes": {"code": "CAD", "minor_units": 677, "decimals": 2},
    "price_excluding_taxes": {"code": "CAD", "minor_units": 599, "decimals": 2},
    "total_applied_taxes": {"code": "CAD", "minor_units": 78, "decimals": 2},
    "sales_taxes": [{...}],
    "total_price": {"code": "CAD", "minor_units": 677, "decimals": 2},
    "pickup_location": {...},
    "can_be_rated": False,
    "is_rated": True,
    "should_be_excluded_from_expense_rating": False,
    "overall_rating": 4,
    "time_of_purchase": "2025-04-30T19:21:35Z",
    "store_id": "441961",
    "store_name": "Daan Go Cake Lab",
    "store_branch": "Scarborough",
    "store_logo": {...},
    "item_id": "376271",
    "item_name": "Surprise Bag Small",
    "item_category": "BAKED_GOODS",
    # "item_logo": {...},
    "item_cover_image": {...},
    "food_handling_instructions": "",
    "is_buffet": False,
    "item_collection_info": "Unit 11",
    "can_user_supply_packaging": False,
    "packaging_option": "MUST_BRING_BAG",
    "pickup_window_changed": False,
    "can_show_best_before_explainer": False,
    "show_sales_taxes": True,
    "order_type": "MAGICBAG",
    "is_support_available": True,
    "redeeming_user_id": "57927099417606817",
    "has_dynamic_price": False,
    "is_eligible_for_reward": False,
    "last_updated_at_utc": "2025-05-02T19:40:50Z",
    "redeemed_at_utc": "2025-04-30T20:45:55Z",
    "has_multiple_payments": True,
    # 'total_price_paid_with_external_provider': None,
    "total_price_paid_with_voucher": {"code": "CAD", "minor_units": 677, "decimals": 2},
    "payment_method_display_name": "Voucher",
    # 'payment_state': None,
    # 'cancelling_entity': None,
    # 'expected_bank_processing_days': None,
    # 'cancelled_or_refunded_at_utc': None,
    # 'support_request_created_at_utc': None,
    "is_donation": False,
}
